"""
Summarizer service — per-chunk LLM summaries + hierarchical (RAPTOR-style) rollup.

What it produces
────────────────
1. LEAF SUMMARIES   — a concise 1-3 sentence abstractive summary for every leaf
                      chunk. Stored on Chunk.summary. Later embedded separately
                      (Chunk.summary_embedding) so retrieval can match on either
                      the verbatim content vector OR the gist vector.

                      Summaries are **category-aware**: each category gets a
                      focused system prompt so the summary is grounded in the
                      right extraction context, producing independent lanes:

                        Content → [Chunk] → [Knowledge] → {Summary:Knowledge}
                          → {summary, content, summary_embedding, content_embedding}
                        Content → [Chunk] → [Keyword]   → {Summary:Keyword}
                          → {summary, keyword, summary_embedding, keyword_embedding}
                        Content → [Chunk] → [Persona]   → {Summary:Persona}
                          → {summary, persona, summary_embedding, persona_embedding}
                        Content → [Chunk] → [Workflow]  → {Summary:Workflow}
                          → {summary, workflow, summary_embedding, workflow_embedding}
                      (features and entities follow the same shape)

2. ROLLUP SUMMARIES — walking the existing parent→child tree bottom-up, each
                      branch node's summary is generated by summarizing its
                      children's summaries. This fills the branch chunks (which
                      the old chunker left as "first paragraph" stubs) with real
                      synthesized gist, and gives you the N-level summary tree
                      the design calls for — one summary per node, parent = the
                      summary of its children.

3. CATEGORY / DOC OVERVIEW — the top of the rollup: a summary of the roots'
                      summaries per category, and one document-level
                      "summary of summaries". This is what feeds the *_OVERVIEW
                      markdown, as opposed to the raw per-type summary dumps.

Design notes
────────────
- Reuses the existing LLMService (IBM AIM via curl) through a single added
  method, `complete_batch`, so all the TLS/curl handling lives in one place.
- Every LLM path has a deterministic extractive fallback (first-sentence(s))
  so the pipeline still completes with LLM_ENABLED=false.
- Batched + concurrent: leaf summaries are chunked into batches and fired
  through the provider's existing concurrency-bounded gather.
- Per-category passes are batched independently so a single
  complete_batch() call per category keeps the rate-limit behaviour
  consistent with the rest of the pipeline.
"""
from __future__ import annotations

import re
from collections import defaultdict
from typing import Optional

from src.models import Chunk
from src.utils.logging import get_logger

logger = get_logger(__name__)

# ── Prompts ───────────────────────────────────────────────────────────────────

# Generic leaf summariser (fallback when category has no dedicated prompt).
_LEAF_SYS = (
    "You are a precise technical summarizer writing summaries that must be "
    "retrievable by a user's question via semantic search. For each numbered "
    "excerpt, write a faithful 1-3 sentence summary that a question about its "
    "topic would match.\n"
    "RETRIEVAL RULES (critical):\n"
    "- START with the excerpt's subject — the exact term, entity, feature, "
    "role, or task name — then state what it IS or DOES. "
    "e.g. 'S-TAP (Software TAP) is a software agent that...'.\n"
    "- Expand every acronym on first use, keeping the acronym: 'GIM (Guardium "
    "Installation Manager)'.\n"
    "- Answer the implicit question the excerpt raises (what it stands for, what "
    "it does, how to do it), in the first sentence.\n"
    "- No filler openers ('This section', 'The following', 'It describes'). "
    "No chunk/heading references.\n"
    "- Ground every statement in the excerpt; never invent. Compress, don't copy.\n"
    "Output ONLY blocks in this exact form, nothing else:\n\n"
    "===N===\n<summary sentence(s)>\n"
)

# ── Category-aware leaf summariser prompts ────────────────────────────────────
# Each lane (knowledge / keyword / persona / workflow / feature / entity) gets
# a focused system prompt so the summary mirrors the extraction schema and the
# resulting {summary, content, summary_embedding, content_embedding} quad is
# retrieval-optimised for that category's query patterns.

_LEAF_SYS_KNOWLEDGE = (
    "You are a precise technical summarizer for KNOWLEDGE chunks. "
    "For each numbered excerpt, write a 1-3 sentence answer-first summary that "
    "captures what the concept IS, how it works, and why it matters. "
    "State the exact concept name first. Ground every sentence in the excerpt. "
    "No filler openers. Compress, don't copy.\n"
    "Output ONLY blocks in this exact form, nothing else:\n\n"
    "===N===\n<summary sentence(s)>\n"
)

_LEAF_SYS_KEYWORDS = (
    "You are a precise technical summarizer for KEYWORD / GLOSSARY chunks. "
    "For each numbered excerpt, write a single complete sentence that states: "
    "ACRONYM(Full Name): what it IS and what it DOES. "
    "Format: 'TERM(Full Name): One complete sentence.' "
    "If not an acronym: 'TermName(TermName): definition.' "
    "Ground every word in the excerpt; never invent.\n"
    "Output ONLY blocks in this exact form, nothing else:\n\n"
    "===N===\n<TERM(Full Name): sentence.>\n"
)

_LEAF_SYS_PERSONAS = (
    "You are a precise technical summarizer for PERSONA chunks. "
    "For each numbered excerpt, write a 1-3 sentence summary that names the "
    "canonical persona archetype first, then states their primary "
    "responsibilities, the key features they use, and the main workflows they run. "
    "Ground every statement in the excerpt; never invent.\n"
    "Output ONLY blocks in this exact form, nothing else:\n\n"
    "===N===\n<summary sentence(s)>\n"
)

_LEAF_SYS_WORKFLOWS = (
    "You are a precise technical summarizer for WORKFLOW chunks. "
    "For each numbered excerpt, write a 1-3 sentence summary that states the "
    "workflow NAME first, its TYPE (Navigation | Configuration | Action), then "
    "the key steps or purpose. Ground every statement in the excerpt; never invent.\n"
    "Output ONLY blocks in this exact form, nothing else:\n\n"
    "===N===\n<summary sentence(s)>\n"
)

_LEAF_SYS_FEATURES = (
    "You are a precise technical summarizer for FEATURE chunks. "
    "For each numbered excerpt, write a 1-3 sentence summary that states the "
    "feature NAME first, what it DOES and its benefit, then any key "
    "platform/database constraints. Ground every statement in the excerpt; never invent.\n"
    "Output ONLY blocks in this exact form, nothing else:\n\n"
    "===N===\n<summary sentence(s)>\n"
)

_LEAF_SYS_ENTITIES = (
    "You are a precise technical summarizer for ENTITY chunks. "
    "For each numbered excerpt, write a 1-3 sentence summary that names the "
    "entity first, states what TYPE of entity it is, then its purpose or role "
    "in the system. Ground every statement in the excerpt; never invent.\n"
    "Output ONLY blocks in this exact form, nothing else:\n\n"
    "===N===\n<summary sentence(s)>\n"
)

# Map ChunkCategory.value → dedicated leaf system prompt.
# Falls back to the generic _LEAF_SYS for any unrecognised category.
_LEAF_SYS_BY_CATEGORY: dict[str, str] = {
    "knowledge": _LEAF_SYS_KNOWLEDGE,
    "keywords":  _LEAF_SYS_KEYWORDS,
    "personas":  _LEAF_SYS_PERSONAS,
    "workflows": _LEAF_SYS_WORKFLOWS,
    "features":  _LEAF_SYS_FEATURES,
    "entities":  _LEAF_SYS_ENTITIES,
}

_ROLLUP_SYS = (
    "You are a precise technical summarizer. Below are child summaries that all "
    "belong to one section. Write a single cohesive 2-4 sentence summary that "
    "captures the section's overall purpose and the key points across its "
    "children. Ground every statement in the provided summaries; never invent. "
    "Output ONLY the summary paragraph — no heading, no preamble."
)

_OVERVIEW_SYS = (
    "You are a precise technical summarizer. Below are section-level summaries "
    "from one document. Write a concise 3-5 sentence overview: what the document "
    "covers, its primary purpose, and the main topics/roles/procedures involved. "
    "Ground every statement in the summaries; never invent. Output ONLY the "
    "overview paragraph."
)

_SENT_SPLIT = re.compile(r"(?<=[.!?])\s+(?=[A-Z(0-9])")


# ── Extractive fallbacks (LLM disabled) ───────────────────────────────────────

def _extractive_summary(text: str, max_sentences: int = 2, max_chars: int = 320) -> str:
    """First N complete sentences — deterministic, never mid-word."""
    body = re.sub(r"^#+\s.*?\n", "", text).strip()
    body = re.sub(r"\s+", " ", body)
    if not body:
        return ""
    sents = _SENT_SPLIT.split(body)
    out, total = [], 0
    for s in sents:
        s = s.strip()
        if not s:
            continue
        out.append(s)
        total += len(s)
        if len(out) >= max_sentences or total >= max_chars:
            break
    summary = " ".join(out)
    return summary[:max_chars].rstrip()


def _parse_blocks(response: str, n: int) -> list[str]:
    """Split an LLM response on ===N=== markers into n ordered slots."""
    results = [""] * n
    parts = re.split(r"={2,}\s*(\d+)\s*[=:]{1,3}", response)
    i = 1
    while i + 1 < len(parts):
        try:
            idx = int(parts[i].strip()) - 1
            if 0 <= idx < n:
                results[idx] = parts[i + 1].strip()
        except ValueError:
            pass
        i += 2
    return results


# ── Service ───────────────────────────────────────────────────────────────────

class SummarizerService:
    """
    Fills Chunk.summary for every chunk (leaves first, then branch rollups) and
    returns per-category + document overviews built from those summaries.
    """

    _LEAF_BATCH = 15  # excerpts per LLM request (matches LLMService batching)

    def __init__(self, llm_service=None, settings=None):
        if settings is None:
            from src.config.settings import get_settings
            settings = get_settings()
        if llm_service is None:
            from src.services.ingestion.llm_service import LLMService
            llm_service = LLMService(settings)
        self._llm = llm_service
        self._settings = settings

    @property
    def _enabled(self) -> bool:
        return getattr(self._llm, "enabled", False)

    # ── 1. Leaf summaries ─────────────────────────────────────────────────────

    def summarize_leaves(self, chunks: list[Chunk]) -> None:
        """Populate .summary on every leaf chunk.

        Independent extraction lanes: leaves are grouped by ChunkCategory and
        each group is summarised with a category-specific system prompt so the
        summary is grounded in the right extraction context.

        Pipeline per category:
            Content → [Chunk] → [<Category>]
              → LLM summary with _LEAF_SYS_BY_CATEGORY[<category>]
              → {summary, content, summary_embedding, content_embedding}

        Each chunk is summarised from ITS OWN content — no borrowing from a
        parent block. The summary is answer-first (subject stated first) so a
        user question about the topic matches it. The section name is
        additionally prepended at embedding time (EmbeddingService._embed_text);
        the stored .summary stays clean.
        """
        leaves = [c for c in chunks if c.metadata.is_leaf]
        if not leaves:
            return

        # Extractive baseline first (guarantees a non-empty summary per chunk).
        for c in leaves:
            if not c.summary:
                c.summary = _extractive_summary(c.content)

        if not self._enabled:
            logger.info("Summarizer: LLM disabled — %d extractive leaf summaries",
                        len(leaves))
            return

        # Group leaves by category so each gets the right system prompt.
        # This is the key change: instead of one generic pass over all leaves,
        # we run one complete_batch() call per category.
        by_cat: dict[str, list[Chunk]] = defaultdict(list)
        for c in leaves:
            if len(c.content.strip()) >= 60:
                by_cat[c.metadata.chunk_type.value].append(c)

        total_targets = sum(len(v) for v in by_cat.values())
        logger.info(
            "Summarizer: LLM leaf pass  categories=%d  total_targets=%d",
            len(by_cat), total_targets,
        )

        for cat, targets in by_cat.items():
            system = _LEAF_SYS_BY_CATEGORY.get(cat, _LEAF_SYS)
            batches = [targets[i:i + self._LEAF_BATCH]
                       for i in range(0, len(targets), self._LEAF_BATCH)]
            requests: list[tuple[str, str]] = []
            for batch in batches:
                lines = []
                for seq, c in enumerate(batch, 1):
                    name = (c.metadata.headings or ["(section)"])[0]
                    snippet = re.sub(r"\s+", " ", c.content.strip())[:600]
                    lines.append(f"--- Excerpt {seq} (subject: {name}) ---\n{snippet}")
                requests.append((system, "\n\n".join(lines)))

            logger.info(
                "Summarizer: category=%s  batches=%d  leaves=%d",
                cat, len(batches), len(targets),
            )
            responses = self._llm.complete_batch(requests)
            for batch, raw in zip(batches, responses):
                if not raw:
                    continue
                slots = _parse_blocks(raw, len(batch))
                for c, s in zip(batch, slots):
                    if s and s.strip():
                        c.summary = s.strip()

    # ── 2. Bottom-up rollup over the tree ─────────────────────────────────────

    def rollup(self, chunks: list[Chunk]) -> None:
        """
        Fill branch-node .summary bottom-up: each branch = summary of its
        children's summaries. Processes deepest branches first so a parent
        always sees already-summarized children.

        All rollup LLM calls at a given depth level are batched into a single
        complete_batch() call instead of firing one asyncio.run() per branch.
        """
        by_id: dict[str, Chunk] = {c.chunk_id: c for c in chunks}
        children: dict[str, list[str]] = defaultdict(list)
        for c in chunks:
            if c.metadata.parent_id:
                children[c.metadata.parent_id].append(c.chunk_id)

        branches = [c for c in chunks if not c.metadata.is_leaf]
        # Deepest first so a parent always sees already-summarized children.
        branches.sort(key=lambda c: c.metadata.depth, reverse=True)

        # Apply extractive fallback to branches with no child summaries up front.
        pending: list[Chunk] = []
        pending_users: list[str] = []
        for branch in branches:
            child_summaries = [
                by_id[cid].summary
                for cid in children.get(branch.chunk_id, [])
                if by_id.get(cid) and by_id[cid].summary
            ]
            if not child_summaries:
                if not branch.summary:
                    branch.summary = _extractive_summary(branch.content)
                continue
            joined = "\n".join(f"- {s}" for s in child_summaries if s.strip())
            heading = " > ".join(branch.metadata.headings) if branch.metadata.headings else ""
            user = (f"Section: {heading}\n\n{joined}" if heading else joined)[:4000]
            pending.append(branch)
            pending_users.append(user)

        if not pending:
            return

        if not self._enabled:
            for branch, user in zip(pending, pending_users):
                all_summaries = [s.lstrip("- ") for s in user.split("\n") if s.startswith("- ")]
                branch.summary = _extractive_summary(" ".join(all_summaries),
                                                     max_sentences=4, max_chars=600)
            return

        logger.info("Summarizer: rollup batch  branches=%d", len(pending))
        requests = [(_ROLLUP_SYS, u) for u in pending_users]
        responses = self._llm.complete_batch(requests)
        for branch, raw, user in zip(pending, responses, pending_users):
            text = (raw or "").strip()
            if not text:
                all_summaries = [s.lstrip("- ") for s in user.split("\n") if s.startswith("- ")]
                text = _extractive_summary(" ".join(all_summaries), max_sentences=4, max_chars=600)
            branch.summary = text

    # ── 3. Category + document overviews ──────────────────────────────────────

    def build_overviews(self, chunks: list[Chunk]) -> dict[str, str]:
        """
        Return {category: overview} plus a "_document" key: the summary of
        summaries. Built from the highest-level (smallest depth) summaries.

        All category overview LLM calls are batched into a single complete_batch()
        call, then the document-level overview fires as one more batch call.
        """
        by_cat: dict[str, list[Chunk]] = defaultdict(list)
        for c in chunks:
            by_cat[str(c.metadata.chunk_type)].append(c)

        # Collect per-category inputs.
        cat_keys: list[str] = []
        cat_users: list[str] = []
        cat_fallback_summaries: list[list[str]] = []
        for cat, cs in by_cat.items():
            if not cs:
                continue
            min_depth = min(c.metadata.depth for c in cs)
            roots = [c.summary for c in cs
                     if c.metadata.depth == min_depth and c.summary] or \
                    [c.summary for c in cs if c.summary]
            if not roots:
                continue
            joined = "\n".join(f"- {s}" for s in roots if s.strip())
            cat_keys.append(cat)
            cat_users.append((f"Section: {cat}\n\n{joined}")[:4000])
            cat_fallback_summaries.append(roots)

        if not cat_keys:
            return {}

        overviews: dict[str, str] = {}
        if not self._enabled:
            for cat, roots in zip(cat_keys, cat_fallback_summaries):
                overviews[cat] = _extractive_summary(" ".join(roots),
                                                     max_sentences=4, max_chars=600)
        else:
            logger.info("Summarizer: overview batch  categories=%d", len(cat_keys))
            responses = self._llm.complete_batch(
                [(_OVERVIEW_SYS, u) for u in cat_users]
            )
            for cat, raw, roots in zip(cat_keys, responses, cat_fallback_summaries):
                text = (raw or "").strip()
                overviews[cat] = text or _extractive_summary(" ".join(roots),
                                                              max_sentences=4, max_chars=600)

        # Document-level: one more single call summarising all category overviews.
        cat_level_summaries = [f"[{cat}] {overviews[cat]}" for cat in cat_keys if cat in overviews]
        if cat_level_summaries:
            joined = "\n".join(f"- {s}" for s in cat_level_summaries if s.strip())
            user = (f"Section: document\n\n{joined}")[:4000]
            if self._enabled:
                out = self._llm.complete_batch([(_OVERVIEW_SYS, user)])
                text = (out[0] if out else "").strip()
            else:
                text = ""
            overviews["_document"] = text or _extractive_summary(
                " ".join(cat_level_summaries), max_sentences=4, max_chars=600
            )
        return overviews

    # ── Shared group summarizer ───────────────────────────────────────────────

    def _summarize_group(self, summaries: list[str], heading: str = "",
                         system: str = _ROLLUP_SYS) -> str:
        """Single-group helper — used only by external callers. Internal paths
        use rollup() and build_overviews() which batch all calls at once."""
        joined = "\n".join(f"- {s}" for s in summaries if s.strip())
        if not joined:
            return ""
        if not self._enabled:
            return _extractive_summary(" ".join(summaries), max_sentences=4, max_chars=600)
        user = (f"Section: {heading}\n\n{joined}" if heading else joined)[:4000]
        out = self._llm.complete_batch([(system, user)])
        text = (out[0] if out else "").strip()
        return text or _extractive_summary(" ".join(summaries), max_sentences=4, max_chars=600)


# ── One-call convenience ──────────────────────────────────────────────────────

def summarize_tree(chunks: list[Chunk], llm_service=None,
                   settings=None) -> dict[str, str]:
    """
    Run the full summary pass over a chunk tree:
        leaves → rollup → overviews.
    Mutates chunks in place (fills .summary) and returns the overview dict.
    """
    svc = SummarizerService(llm_service=llm_service, settings=settings)
    svc.summarize_leaves(chunks)
    svc.rollup(chunks)
    return svc.build_overviews(chunks)
